//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFirmaCagri1.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbis_TakipEntities4 : DbContext
    {
        public dbis_TakipEntities4()
            : base("name=dbis_TakipEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbladmin> tbladmin { get; set; }
        public virtual DbSet<tblcagridetay> tblcagridetay { get; set; }
        public virtual DbSet<tblcagrilar> tblcagrilar { get; set; }
        public virtual DbSet<tbldepartmanlar> tbldepartmanlar { get; set; }
        public virtual DbSet<tblfirmalar> tblfirmalar { get; set; }
        public virtual DbSet<tblgorevdetaylar> tblgorevdetaylar { get; set; }
        public virtual DbSet<tblgorevler> tblgorevler { get; set; }
        public virtual DbSet<tblmesajlar> tblmesajlar { get; set; }
        public virtual DbSet<tblpersonel> tblpersonel { get; set; }
    }
}
